import { SecurityReport } from "./solana";

export function generateRiskSummary(report: SecurityReport): string {
  const risks: string[] = [];
  const pros: string[] = [];

  if (report.isMintable) risks.push("Mint Authority is still enabled (developer can print infinite tokens).");
  else pros.push("Mint Authority is revoked (supply is fixed).");

  if (report.isFreezable) risks.push("Freeze Authority is enabled (developer can blacklist wallets).");
  else pros.push("Freeze Authority is revoked (wallets cannot be frozen).");

  if (report.isMutable) risks.push("Metadata is mutable (developer can change token name/image).");
  else if (report.isMutable === false) pros.push("Metadata is immutable.");

  const top1 = report.topHolders[0]?.percentage || 0;
  if (top1 > 30) risks.push(`Whale alert: Top holder owns ${top1.toFixed(1)}% of supply.`);
  else pros.push("Holder distribution looks healthy (no single whale > 30%).");

  // Advanced Market Analysis
  if (report.marketData) {
     const { liquidityUsd, volume24h, marketCap, fdv, priceChange24h, name } = report.marketData;

     // Deprecated / De-pegged Asset Checks
     if (name.includes("(Sollet)") || name.includes("Wrapped Ethereum (Sollet)") || name.includes("soETH")) {
         risks.unshift("🚨 **CRITICAL: Deprecated Asset (Sollet).** This token is a legacy wrapped asset from the deprecated Sollet bridge. It is likely de-pegged and trading significantly below the real asset price.");
     }
     
     // Liquidity Analysis
     if (liquidityUsd < 1000) risks.push("🚨 **CRITICAL: Liquidity is negligible (< $1,000).** High risk of rugpull or inability to sell.");
     else if (liquidityUsd < 10000) risks.push("Liquidity is low (< $10k). Price impact on sells will be high.");
     else if (liquidityUsd > 100000) pros.push("💧 **Deep Liquidity:** > $100k liquidity ensures smoother trading.");

     // Volatility / Activity
     if (volume24h > liquidityUsd * 2) risks.push("High Volatility: 24h Volume is > 2x Liquidity. Expect wild price swings.");
     
     // Price Momentum
     if (priceChange24h < -50) risks.push(`Bearish Momentum: Token is down ${priceChange24h.toFixed(1)}% in 24h.`);
     else if (priceChange24h > 100) pros.push(`🚀 **Pump Alert:** Token is up ${priceChange24h.toFixed(1)}% in 24h.`);

     // Valuation Check
     if (fdv > marketCap * 1.5) risks.push("Vest Schedule Warning: FDV is significantly higher than Market Cap. Large unlocks may dump price.");
  } else {
    risks.push("No liquidity found on major DEXes. Token might be unlisted or dead.");
  }

  let summary = `### 🤖 AI Security Verdict: **${report.verdict}**\n\n`;
  summary += `**Risk Score:** ${report.riskScore}/100 (Lower is safer)\n\n`;

  if (risks.length > 0) {
    summary += "#### ⚠️ Risk Factors\n" + risks.map(r => `- ${r}`).join("\n") + "\n\n";
  }
  
  if (pros.length > 0) {
    summary += "#### ✅ Safety Indicators\n" + pros.map(p => `- ${p}`).join("\n") + "\n\n";
  }

  summary += `\n*Analysis generated by Solana Guard AI based on on-chain data.*`;

  return summary;
}
